### PR TITLE
[Fiber] Ensure `useEffectEvent` reads latest values in `forwardRef` and `memo()` Components

### LINKED ISSUE #34818: Bug: Stale closures with `useEffectEvent`
React version: 19.2

## Steps To Reproduce

1. Open [the reduced test case](https://stackblitz.com/edit/github-utjrgufd?file=app%2Froot.tsx) and view the console
2. Click the "Home" link (this causes `navigationType` to change to `REPLACE`)

```tsx
function App() {
  const navigationType = useNavigationType();
  // ✅ This is REPLACE after clicking the link.
  console.log('render', navigationType);

  const fn = useEffectEvent(() => {
    // ❌ But this is always POP. It's not seeing the latest value!
    console.log('effect event', navigationType);
  });
  useEffect(() => {
    setInterval(() => {
      fn();
    }, 3000);
  }, []);

  return (
    <>
      <Link to="/">Home</Link>
      <Outlet />
    </>
  );
}

// 🤷‍♂️ Removing `memo` here fixes the problem.
export default memo(App);
```

Link to code example:

https://stackblitz.com/edit/github-utjrgufd?file=app%2Froot.tsx

## The current behavior

The Effect Event receives a stale value from `navigationType` (`POP`).

Image

## The expected behavior

The Effect Event should receive the latest value from `navigationType` (`REPLACE`).

### PR DESCRIPTION
**Pull request by eps1lon**
Closes https://github.com/facebook/react/issues/34818

Seems to me the event payload handling should've gone into the original fallthrough block instead of just handling it for `FunctionComponent`: https://github.com/facebook/react/pull/25229/files#diff-9e8ee221dbf99e0ccdad6a63bf63804dea26f1785e2f443dbe92fa835a63b83eL412-L415

See first commit for current behavior where Effect Events did not read the latest Context value if used in `React.memo` Components.

### CODE REVIEW

File: packages/react-reconciler/src/__tests__/useEffectEvent-test.js [hunk 1]
```diff
@@ -850,4 +850,82 @@ describe('useEffectEvent', () => {
...
+    let logContextValue;
+    const ContextReader = React.memo(function ContextReader() {
+      const value = useContext(MyContext);
+      Scheduler.log('ContextReader: ' + value);
+      const fireLogContextValue = useEffectEvent(() => {
+        Scheduler.log('ContextReader (Effect event): ' + value);
+      });
+      useEffect(() => {
+        logContextValue = fireLogContextValue;
+      }, []);
```
Comment (eps1lon) [inline packages/react-reconciler/src/__tests__/useEffectEvent-test.js:866]: The original report registered an interval here. Even after rendering with a new context value, the interval continued to log the initial value.

**Review by sebmarkbage — APPROVED** [review]

**Comment by controversial** [comment]
@eps1lon any hope of getting this picked into a stable release? Judging by the amount of mentions in this thread, and the comments on https://github.com/react/react/issues/35187, it seems like this blocks quite a few people from adopting useEffectEvent
