### PR TITLE
[Flight] allow context providers from client modules

### LINKED ISSUE #35340: Bug: Server Components error when directly rendering a Context
A Server Component that renders `<Context>` directly will result in a runtime error:

> Element type is invalid. Received a promise that resolves to: Context. Lazy element type must resolve to a class or function.

[Here's the minimum repro](https://github.com/samselikoff/2025-12-09-render-context-from-rsc):

```tsx
import { Context } from './context';

export default function Home() {
  return <Context value={2}>hello</Context>;
}
```

```tsx
// context.tsx
'use client';

import { createContext } from 'react';

export const Context = createContext(1);
```

React version: 19.3.0-canary-378973b3-20251205

Link to code example:

https://github.com/samselikoff/2025-12-09-render-context-from-rsc

## The current behavior

Renders without error

## The expected behavior

Errors with

> Element type is invalid. Received a promise that resolves to: Context. Lazy element type must resolve to a class or function.

### PR DESCRIPTION
**Pull request by rickhanlonii**
Allows Server Components to import Context from a `"use client'` module and render its Provider. 

That means you can now import Context in a server component and pass it a value for the Client to read without a client component wrapper:

```js
import {Context, ClientCompoent} from './Client';


export function App() {
  return (
    <Context value="from server">
      <ClientComponent />
    </Context>
  );
}

```

```js
// Client.js
"use client"

export const Context = createContext(null);

export function ClientComponent() {
  return <div>{use(Context)}</div>
}
```

Note: this is not server context. It's just creating the Context with a value from the server in the client bundle. You cannot `use(Context)` in a server component.

Only tricky part was that I needed to add `REACT_CONTEXT_TYPE` handling in mountLazyComponent so lazy-resolved Context types can be rendered. Previously only functions, REACT_FORWARD_REF_TYPE, and REACT_MEMO_TYPE were handled.

Tested in the Flight fixture.

ty bb claude

Closes https://github.com/facebook/react/issues/35340

### CODE REVIEW

**Comment by samselikoff** [comment]
Closes https://github.com/facebook/react/issues/35340

File: fixtures/flight/src/ClientContext.js [hunk 1]
```diff
@@ -0,0 +1,12 @@
+'use client';
+
+import {createContext, use} from 'react';
```
Comment (eps1lon) [inline fixtures/flight/src/ClientContext.js:3]: Seems like Flight fixture is failing in CI: 
> [WebServer] [1] ReferenceError: React is not defined
> [WebServer] [1]     at ClientReadContext (file:///home/runner/work/react/react/fixtures/flight/src/ClientContext.js:8:3)
-- https://github.com/facebook/react/actions/runs/21616149809/job/62295291365?pr=35675#step:13:236

I'll check what's wrong with our transform. Until then a `import * as React from 'react'` at the top level fixes it. The other Client modules also have that.

**Review by eps1lon — APPROVED** [review]

File: fixtures/flight/src/ClientContext.js (hunk 1 above)
Comment (eps1lon) [reply fixtures/flight/src/ClientContext.js:3]: Fixed in https://github.com/facebook/react/pull/35677

File: packages/react-server/src/ReactFlightServerTemporaryReferences.js [hunk 2]
```diff
@@ -65,11 +65,10 @@ const proxyHandlers: Proxy$traps<mixed> = {
...
       case 'Provider':
-        throw new Error(
-          `Cannot render a Client Context Provider on the Server. ` +
-            `Instead, you can export a Client Component wrapper ` +
-            `that itself renders a Client Context Provider.`,
-        );
+        // Context.Provider === Context in React, so return the same reference.
+        // This allows server components to render <ClientContext.Provider>
+        // which will be serialized and executed on the client.
+        return receiver;
```
Comment (acdlite) [inline packages/react-server/src/ReactFlightServerTemporaryReferences.js:71]: This is a bug. This is only correct if it's a React Context object, but nothing in this path performs that check.
